/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gqfast_global_JNILoader */

#ifndef _Included_gqfast_global_JNILoader
#define _Included_gqfast_global_JNILoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gqfast_global_JNILoader
 * Method:    cpp_open_loader
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gqfast_global_JNILoader_cpp_1open_1loader
  (JNIEnv *, jobject);

/*
 * Class:     gqfast_global_JNILoader
 * Method:    cpp_close_loader
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gqfast_global_JNILoader_cpp_1close_1loader
  (JNIEnv *, jobject);

/*
 * Class:     gqfast_global_JNILoader
 * Method:    cpp_load_index
 * Signature: (Ljava/lang/String;I[I)V
 */
JNIEXPORT void JNICALL Java_gqfast_global_JNILoader_cpp_1load_1index
  (JNIEnv *, jobject, jstring, jint, jintArray);

/*
 * Class:     gqfast_global_JNILoader
 * Method:    run_query_aggregate_int
 * Signature: (Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_gqfast_global_JNILoader_run_1query_1aggregate_1int
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     gqfast_global_JNILoader
 * Method:    run_query_aggregate_double
 * Signature: (Ljava/lang/String;I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_gqfast_global_JNILoader_run_1query_1aggregate_1double
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
